@startuml tressette{
    package model{
        class Card{
            - rank : Rank
            - suit : Suit
        }
        class Deck{
            - cards : List<Card>
            + shuffle() : void
            + draw() : Card
        }
        enum Suit{

        }
        enum Rank{
            
        }
        interface GameRules{
            + solveTable(table : Table) : Player
            + computeScore(List<Card>) : int
            + moveIsLegal(table : Table, cardPlayed : Card, player : Player)
        }
        class TresetteRules implements GameRules{
        }
        class Game{
            - rules : GameRules
            - numberOfPlayers : int
            - players : List<Player>
            - teams : Map<Team, List<Player>>
            - deck : Deck
            - table : Table
            - currentPlayer : int
            - currentPhase : Phase
            + dealCard(player: Player) : void
            + changePhase(phase : Phase) : void
            + askPlayerForCard(player : Player) : Card
            + addCardToTable(card : Card) : void
            + solveTable(table : Table) : void
            + addCardsToPlayerPile(table : Table, player : Player) : void
            + updatePlayerOrder(player : Player) : void
            + computeScore(team : Team) : int
            + computeWinningTeam() : Team
        }
        enum Phase{
            + INITIALIZATION
            + TURN
            + WAIT_HUMAN_PLAY
            + ENDGAME
        }
        class Hand{
            - cards : List<Card>
        }
        class Table{
            - cards : LinkedHashMap<Player,Card>
            + addCard(card : Card, player : Player) : void 
            + clear() : void
        }
        class Team{
            - pile : List<Card>
        }
        abstract Player{
            - hand : Hand
            - team : Team
            + receiveCard(card : Card) : void
            + playCard() : Card
            + getTeam() : Team
            + addCardsToTeamPile(card : Card...) : void
        }
        class HumanPlayer extends Player{
            
        }
        class AIPlayer extends Player{
            - strategy : AiStrategy
        }
        interface AiStrategy{

        }
        Game --o GameRules
        Game --* Team
        Game --* Deck
        Game --* Table
        Game --* "2..4" Player
        Game --* Phase
        Player --o Team
        Player --* Hand
        AIPlayer --* AiStrategy
        Deck --o Card
        Table --o Card
        Hand --o Card
        Card --> Suit
        Card --> Rank
    }
    package controller{

    }
    package view{

    }
}